define({
    MARK_AS_READ: 'Пометить (не) прочитанным',
    DELETE: 'Удалить',
    UPDATE: 'Обновить',
    PRINT: 'Печатать',
    SEARCH: 'Искомая статья',
    SEARCH_TIP: 'Используйте «:» для поиска по содержимому.',
    NEVER: 'Никогда',
    EVERY_5_MINUTES: 'Каждые 5 минут',
    EVERY_15_MINUTES: 'Каждые 15 минут',
    EVERY_30_MINUTES: 'Каждые 30 минут',
    EVERY_HOUR: 'Каждый час',
    EVERY_2_HOURS: 'Каждые 2 часа',
    EVERY_3_HOURS: 'Каждые 3 часа',
    EVERY_5_HOURS: 'Каждые 5 часов',
    EVERY_10_HOURS: 'Каждые 10 часов',
    EVERY_24_HOURS: 'Каждый день',
    EVERY_WEEK: 'Каждую неделю',
    USERNAME: 'Имя пользователя',
    PASSWORD: 'Пароль',
    CANCEL: 'Отменить',
    OK: 'Хорошо',
    LAYOUT: 'Вид',
    LINES: 'Линии',
    SORT_ORDER: 'Порядок сортировки',
    DESCENDING: 'Нисходящий',
    ASCENDING: 'Восходящий',
    ONE_LINE: 'В одну линию',
    TWO_LINES: 'В две линии',
    AUTO: 'Автоматически',
    FULL_ARTICLE: 'Вся статья',
    FULL_ARTICLE_SINGLE: 'Вся статья',
    REALLY_DELETE: 'Вы уверены что хотите отписаться от этого канала?',
    ALL_FEEDS: 'Все каналы',
    PINNED: 'Закреплённое',
    TRASH: 'Корзина',
    MARK_ALL_AS_READ: 'Пометить всё как прочитанное',
    PROPERTIES: 'Подробности',
    REFETCH: 'Обноваить',
    OPENHOME: 'Открыть сайт канала',
    UNDELETE: 'Убрать из корзины',
    NEXT_UNREAD: 'Следущее непрочитанное',
    PREV_UNREAD: 'Предыдущее непрочитанное',
    MARK_AND_NEXT_UNREAD: 'Пометить прочитанным и чатать следущее не прочитанное',
    MARK_AND_PREV_UNREAD: 'Пометить прочитанным и чатать предыдущее не прочитанное',
    PIN: 'От- или закрепить',
    PIN_QUESTION_A: 'Айтем "',
    PIN_QUESTION_B: '" Статья закрепленна, удалить её?',
    MARK_ALL_QUESTION: 'Уверены что хотите пометить все статьи прочитанным?',
    ADD_RSS_SOURCE: 'Подписаться на РСС-канал',
    UPDATE_ALL: 'Обновить всё',
    FETCH_TITLE_TIP: 'Если поле оставить пустым, будет показан заголовок статьи.',
    NAME: 'Имя',
    ADDRESS: 'Адрес',
    PARENT: 'Родительская папка',
    JANUARY: 'Январь',
    FEBRUARY: 'Ферваль',
    MARCH: 'Март',
    APRIL: 'Апрель',
    MAY: 'Май',
    JUNE: 'Июнь',
    JULY: 'Июль',
    AUGUST: 'Август',
    SEPTEMBER: 'Сентябрь',
    OCTOBER: 'Октябрь',
    NOVEMBER: 'Ноябрь',
    DECEMBER: 'Дакбрь',
    MONDAY: 'Понедельник',
    TUESDAY: 'Вторник',
    WEDNESDAY: 'Среда',
    THURSDAY: 'Четверг',
    FRIDAY: 'Пятница',
    SATURDAY: 'Суббота',
    SUNDAY: 'Воскресенье',
    TODAY: 'Сегодня',
    YESTERDAY: 'Вчера',
    LAST_WEEK: 'За последнюю неделю',
    EARLIER_THIS_MONTH: 'Ранее в этом месяце',
    MORE: 'Больше',
    SETTINGS: 'Настройки',
    EMPTY_TRASH: 'Отчистить корзину',
    RSS_FEED_URL: 'Ссылка на РСС: ',
    OPTIONS: 'Настройки',
    UPDATING_FEEDS: 'Обновить каналы',

    UNREAD: 'Непрочитанное',
    TOTAL: 'Всё',
    NEW_FOLDER: 'Новая папка',
    DOWNLOAD: 'Скачать',
    DELETE_ALL_ARTICLES: 'Удалить все статьи',
    DELETE_ALL_Q: 'Вы уверены что хотите удалить все статьи?',
    REALLY_EMPTY_TRASH: 'Вы уверены что хотите отчистить корзину?',
    RENAME: 'Переименовать',
    FOLDER_NAME: 'Имя папки',

    AUTOREMOVE: 'Автоматически удалять после',
    OLDER_THAN_DAY: 'Давнее дня',
    OLDER_THAN_WEEK: 'Давнее недели',
    OLDER_THAN_MONTH: 'Давнее месяца',
    OLDER_THAN_TWO_MONTHS: 'Давнее двух месяцев',

    AUTOREMOVE_SETTING: 'Автоматически удалять',
    USE_GLOBAL_SETTING: 'Использовать глобальные настройки',
    REMOVE_ALL: 'Удалить всё',
    KEEP_UNVISITED: 'Оставить неоткрытым',
    KEEP_UNREAD: 'Оставить непрочитанным',

    SORT_BY: 'Сортировать по',
    DATE: 'Дата',
    TITLE: 'Заголовок',
    AUTHOR: 'Автор',

    SORTING: 'Сортировка',
    SECONDARY_SORTING: 'Второй вариант сортировки',

    HIDE_OVERLAYS: 'Hide overlays',
    TOGGLE_SHOW_ONLY_UNREAD: 'Показывать только непрочитанное',
    STOP_UPDATE: 'Прекратить обновление каналов',
    OPEN_HOME: 'Открыть сайт канала',
    SCROLL_INTO_VIEW: 'Переместиться в обзор',
    FOCUS_FEEDS: 'Сфокусироваться на каналах',
    SELECT_NEXT_FEED: 'Выбрать следущий канал',
    SELECT_PREVIOUS_FEED: 'Выбрать предыдущий канал',
    CLOSE_FOLDERS: 'Закрыть папки',
    OPEN_FOLDERS: 'Открыть папки',
    TOGGLE_FOLDER: 'Пометить папку',
    SHOW_ARTICLES: 'Показать статьи',
    SHOW_AND_FOCUS_ARTICLES: 'Показать и сфокусироваться на статьях',
    SELECT_NEXT_ARTICLE: 'Выбрать следущуюю статью',
    SELECT_PREVIOUS_ARTICLE: 'Выбрать предыдущую статью',
    FOCUS_SEARCH: 'Сфокусироваться на поиске',
    FOCUS_ARTICLES: 'Сфокусироваться на статьях',
    SELECT_ALL_ARTICLES: 'Выбрать все',
    PAGE_UP: 'Страница выше',
    PAGE_DOWN: 'Страница ниже',
    SCROLL_TO_TOP: 'Переместиться в начало',
    SCROLL_TO_BOTTOM: 'Переместиться в конец',
    FOCUS_CONTENT: 'Сфокусироваться на содержимом',
    SCROLL_UP: 'Выше',
    SCROLL_DOWN: 'Ниже',
    
    CHANGE_VIEW: "Изменить вид"
});
